# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Obrary Template
tagline:             Making it easy to make
description:         'Open Design for {{ product }}'
url:                 http://obrary.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Scott Austin
  url:               https://twitter.com/svaustin
  email:             scotta@obrary.com

# Custom vars
version:             1.0.0
product:			 Template
